# Site Settings
title: Vasilis Ethan Sarris
description: A personal website
url: "https://sarrisv.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
keyword: Student, Java, Python, Graph Theory, Neo4j, Computer Science, University of Pittsburgh
username: Vasilis Ethan Sarris

# Personal Settings
user_description: I am a junior pursuing a B.S. in Computer Science at the University of Pittsburgh. Since summer of 2019 I have been working part-time at the University of Pittsburgh's LIFE
user_title: Student - Research Assistant - Graph Theory Enthusiast Lab enjoying whatever projects are thrown my way, currently that happens to be applying various methods of Graph Theory analysis on neuroimaging data. I love Computer Science but at the end of the day I just want to work on some interesting problems and hopefully improve some peoples lives along the way.
email: vas82@pitt.edu
github_link:  https://github.com/sarrisv/
linkedin_link: https://www.linkedin.com/in/vesarris/

# Google-Analytics
google-analytics:
  id: UA-157544690-1 

include: ['_pages', '_writing']
exclude: ['package.json', 'node_modules', 'README.md', '_workspace.code-workspace', '.gitignore']

markdown: kramdown
kramdown: 
  input: GFM
